In [ ]:
import numpy as np
import sys

### **Creazione Array**


In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
a[0],a[1]

array([2, 3])

In [ ]:
a[1:]

array([2, 3, 4])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[1:3]

array([2, 3])

### **Multi Indexing**

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

### **Tipi Di Array**


In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1,2,3,4,5], dtype=float)

array([1., 2., 3., 4., 5.])

In [ ]:
np.array([1,2,3,4,5], dtype=np.int8) #miglior performance

array([1, 2, 3, 4, 5], dtype=int8)

In [ ]:
c = np.array(["a","b","c"])

In [ ]:
c.dtype

dtype('<U1')

### **Dimensione e Forma**

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [ ]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.size

12

In [ ]:
B.ndim

3

In [ ]:
B.shape

(2, 2, 3)

Se la dimensione non combacia, dirà il tipo sarà "oggetto"

In [ ]:
C = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
    ]
])

In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
type(C[0])

list

### **Indexing e Slicing di una Matrice**

In [ ]:
#matrice quadrata
A = np.array([
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10,10,10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### **Operazioni su matrici**

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])

In [ ]:
A.sum()

45

In [ ]:
A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=0) #somma colonne

array([12, 15, 18])

In [ ]:
A.sum(axis=1) #somma righe

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

### **Vettorizzazione e Broadcasting**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10,10,10,10])

In [ ]:
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

### **Boolean Arrays**

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[[0,-1]]

array([0, 3])

In [ ]:
a[[True,False,False,True]]

array([0, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[ (a == 0) | (a == 1) ]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100,size=(3,3))

In [ ]:
A

array([[68, 97, 85],
       [72, 30, 12],
       [31, 78, 61]])

In [ ]:
A[A > 30]

array([68, 97, 85, 72, 31, 78, 61])

### **Algebra Lineare**


In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [ ]:
#prodotto matrici
A.dot(B)
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
#scambio righe con le colonne
B.T

array([[6, 4, 2],
       [5, 3, 1]])

### **Size objects in memory**

### Int,Floats


In [ ]:
#an integer in python is > 24 bytes
sys.getsizeof(1)

28

In [ ]:
#longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
#numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
np.dtype(float).itemsize

8

### List are even larger

In [ ]:
#one element list
sys.getsizeof([1])

64

In [ ]:
#an array wiht on element in numpy
np.array([1]).nbytes

8

### And performance are also better

In [ ]:
l = list(range(1000000))

In [ ]:
a = np.arange(1000000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 3.93 ms, sys: 0 ns, total: 3.93 ms
Wall time: 3.84 ms


333332833333500000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 305 ms, sys: 25.6 ms, total: 331 ms
Wall time: 334 ms


333332833333500000

### **Funzioni Utili con numpy**

Random


In [ ]:
np.random.random(size=2)

array([0.60529739, 0.4595591 ])

In [ ]:
np.random.normal(size=2)

array([0.97406095, 1.15842937])

In [ ]:
np.random.rand(2, 4)

array([[0.15862323, 0.63281205, 0.98901986, 0.6583627 ],
       [0.82578824, 0.77775706, 0.70129281, 0.14508648]])

Arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0,1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

Reshape

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Linespace

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

Zeros, one , empty

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Identity and eye

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
"hello word"[6]

'w'